In [1]:
import os
import csv
import pandas as pd

In [2]:
#data = os.path.join("/../../desktop/resources/movie_scores.csv")
data = os.path.join("..","..","desktop","resources","Pokemon.csv")

In [3]:
df = pd.read_csv(data)
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
ndf = df[["Type 1", "HP"]]
ndf

       Type 1   HP
0       Grass   45
1       Grass   60
2       Grass   80
3       Grass   80
4        Fire   39
5        Fire   58
6        Fire   78
7        Fire   78
8        Fire   78
9       Water   44
10      Water   59
11      Water   79
12      Water   79
13        Bug   45
14        Bug   50
15        Bug   60
16        Bug   40
17        Bug   45
18        Bug   65
19        Bug   65
20     Normal   40
21     Normal   63
22     Normal   83
23     Normal   83
24     Normal   30
25     Normal   55
26     Normal   40
27     Normal   65
28     Poison   35
29     Poison   60
..        ...  ...
770     Fairy   95
771  Fighting   78
772  Electric   67
773      Rock   50
774    Dragon   45
775    Dragon   68
776    Dragon   90
777     Steel   57
778     Ghost   43
779     Ghost   85
780     Ghost   49
781     Ghost   44
782     Ghost   54
783     Ghost   59
784     Ghost   65
785     Ghost   55
786     Ghost   75
787     Ghost   85
788       Ice   55
789       Ice   95
790    Flying   40
791    Flying   85
792     Fairy  126
793      Dark  126
794    Dragon  108
795      Rock   50
796      Rock   50
797   Psychic   80
798   Psychic   80
799      Fire   80

[800 rows x 2 columns]

In [6]:
grouped_df = ndf.groupby(['Type 1'])
grouped_df

In [ ]:
df.count()

In [ ]:
df['Offense Type'].value_counts()

In [ ]:
df['Offense Type'] = df['Offense Type'].replace({'Commercial Sex Acts': 'Prostitution', 'Theft from building': 'Theft', 'stolen property offenses': 'theft'})
df

In [ ]:
df['Offense Type'].value_counts()